services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
    volumes:
      - ./scripts/database:/docker-entrypoint-initdb.d
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
